// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statedb.proto

#include "statedb.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace taraxa {
namespace vm {
namespace statedb {
}  // namespace statedb
}  // namespace vm
}  // namespace taraxa
namespace protobuf_statedb_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "statedb.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rstatedb.proto\022\021taraxa.vm.statedb\032\033goog"
      "le/protobuf/empty.proto\032\014common.proto2\327\002"
      "\n\007StateDB\022>\n\003Put\022\037.taraxa.vm.statedb.Byt"
      "esMessage\032\026.google.protobuf.Empty\022A\n\006Del"
      "ete\022\037.taraxa.vm.statedb.BytesMessage\032\026.g"
      "oogle.protobuf.Empty\022G\n\003Get\022\037.taraxa.vm."
      "statedb.BytesMessage\032\037.taraxa.vm.statedb"
      ".BytesMessage\022F\n\003Has\022\037.taraxa.vm.statedb"
      ".BytesMessage\032\036.taraxa.vm.statedb.BoolMe"
      "ssage\0228\n\005Close\022\027.taraxa.vm.statedb.VmId\032"
      "\026.google.protobuf.EmptyB\tZ\007grpc_gob\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 442);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "statedb.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors();
  ::protobuf_common_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_statedb_2eproto
namespace taraxa {
namespace vm {
namespace statedb {

// @@protoc_insertion_point(namespace_scope)
}  // namespace statedb
}  // namespace vm
}  // namespace taraxa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
