// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statedb.proto

package grpc_go

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BytesMessage struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesMessage) Reset()         { *m = BytesMessage{} }
func (m *BytesMessage) String() string { return proto.CompactTextString(m) }
func (*BytesMessage) ProtoMessage()    {}
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_statedb_39048c983d5df06d, []int{0}
}
func (m *BytesMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesMessage.Unmarshal(m, b)
}
func (m *BytesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesMessage.Marshal(b, m, deterministic)
}
func (dst *BytesMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesMessage.Merge(dst, src)
}
func (m *BytesMessage) XXX_Size() int {
	return xxx_messageInfo_BytesMessage.Size(m)
}
func (m *BytesMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BytesMessage proto.InternalMessageInfo

func (m *BytesMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BoolMessage struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMessage) Reset()         { *m = BoolMessage{} }
func (m *BoolMessage) String() string { return proto.CompactTextString(m) }
func (*BoolMessage) ProtoMessage()    {}
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_statedb_39048c983d5df06d, []int{1}
}
func (m *BoolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMessage.Unmarshal(m, b)
}
func (m *BoolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMessage.Marshal(b, m, deterministic)
}
func (dst *BoolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMessage.Merge(dst, src)
}
func (m *BoolMessage) XXX_Size() int {
	return xxx_messageInfo_BoolMessage.Size(m)
}
func (m *BoolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMessage proto.InternalMessageInfo

func (m *BoolMessage) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*BytesMessage)(nil), "taraxa.vm.statedb.BytesMessage")
	proto.RegisterType((*BoolMessage)(nil), "taraxa.vm.statedb.BoolMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateDBClient is the client API for StateDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateDBClient interface {
	Put(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*BytesMessage, error)
	Has(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*BoolMessage, error)
	Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type stateDBClient struct {
	cc *grpc.ClientConn
}

func NewStateDBClient(cc *grpc.ClientConn) StateDBClient {
	return &stateDBClient{cc}
}

func (c *stateDBClient) Put(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Delete(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Get(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*BytesMessage, error) {
	out := new(BytesMessage)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Has(ctx context.Context, in *BytesMessage, opts ...grpc.CallOption) (*BoolMessage, error) {
	out := new(BoolMessage)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Has", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateDBServer is the server API for StateDB service.
type StateDBServer interface {
	Put(context.Context, *BytesMessage) (*empty.Empty, error)
	Delete(context.Context, *BytesMessage) (*empty.Empty, error)
	Get(context.Context, *BytesMessage) (*BytesMessage, error)
	Has(context.Context, *BytesMessage) (*BoolMessage, error)
	Close(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterStateDBServer(s *grpc.Server, srv StateDBServer) {
	s.RegisterService(&_StateDB_serviceDesc, srv)
}

func _StateDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Put(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Delete(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Get(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BytesMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Has",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Has(ctx, req.(*BytesMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Close(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _StateDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taraxa.vm.statedb.StateDB",
	HandlerType: (*StateDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _StateDB_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StateDB_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StateDB_Get_Handler,
		},
		{
			MethodName: "Has",
			Handler:    _StateDB_Has_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StateDB_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statedb.proto",
}

func init() { proto.RegisterFile("statedb.proto", fileDescriptor_statedb_39048c983d5df06d) }

var fileDescriptor_statedb_39048c983d5df06d = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x49, 0x2c,
	0x49, 0x4d, 0x49, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0x49, 0x2c, 0x4a, 0xac,
	0x48, 0xd4, 0x2b, 0xcb, 0xd5, 0x83, 0x4a, 0x48, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea,
	0x83, 0x15, 0x24, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0xd4, 0x2b, 0xa9, 0x70,
	0xf1, 0x38, 0x55, 0x96, 0xa4, 0x16, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x89, 0x70,
	0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x41, 0x38, 0x4a,
	0xca, 0x5c, 0xdc, 0x4e, 0xf9, 0xf9, 0x39, 0x58, 0x15, 0x71, 0x40, 0x15, 0x19, 0x5d, 0x63, 0xe2,
	0x62, 0x0f, 0x06, 0xd9, 0xe9, 0xe2, 0x24, 0x64, 0xc7, 0xc5, 0x1c, 0x50, 0x5a, 0x22, 0x24, 0xaf,
	0x87, 0xe1, 0x1c, 0x3d, 0x64, 0xeb, 0xa4, 0xc4, 0xf4, 0x20, 0x8e, 0xd3, 0x83, 0x39, 0x4e, 0xcf,
	0x15, 0xe4, 0x38, 0x21, 0x47, 0x2e, 0x36, 0x97, 0xd4, 0x9c, 0xd4, 0x92, 0x54, 0xf2, 0x8d, 0x70,
	0xe7, 0x62, 0x76, 0x4f, 0x25, 0xc2, 0x09, 0x84, 0x14, 0x08, 0xb9, 0x71, 0x31, 0x7b, 0x24, 0x16,
	0x13, 0x36, 0x48, 0x0e, 0x9b, 0x02, 0xa4, 0x50, 0x33, 0xe7, 0x62, 0x75, 0xce, 0xc9, 0x2f, 0x4e,
	0x15, 0xc2, 0xe1, 0x62, 0x5c, 0x3e, 0x71, 0xe2, 0x8c, 0x62, 0x4f, 0x2f, 0x2a, 0x48, 0x8e, 0x4f,
	0xcf, 0x4f, 0x62, 0x03, 0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xf8, 0xda, 0x69,
	0xf6, 0x01, 0x00, 0x00,
}
