// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statedb.proto

package grpc_go

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyMessage struct {
	VmId                 *VmId         `protobuf:"bytes,1,opt,name=vmId,proto3" json:"vmId,omitempty"`
	MemoryAddress        *BytesMessage `protobuf:"bytes,2,opt,name=memoryAddress,proto3" json:"memoryAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KeyMessage) Reset()         { *m = KeyMessage{} }
func (m *KeyMessage) String() string { return proto.CompactTextString(m) }
func (*KeyMessage) ProtoMessage()    {}
func (*KeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_statedb_2a3d28d9a5619618, []int{0}
}
func (m *KeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMessage.Unmarshal(m, b)
}
func (m *KeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMessage.Marshal(b, m, deterministic)
}
func (dst *KeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMessage.Merge(dst, src)
}
func (m *KeyMessage) XXX_Size() int {
	return xxx_messageInfo_KeyMessage.Size(m)
}
func (m *KeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMessage proto.InternalMessageInfo

func (m *KeyMessage) GetVmId() *VmId {
	if m != nil {
		return m.VmId
	}
	return nil
}

func (m *KeyMessage) GetMemoryAddress() *BytesMessage {
	if m != nil {
		return m.MemoryAddress
	}
	return nil
}

type KeyAndValueMessage struct {
	Key                  *KeyMessage   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *BytesMessage `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KeyAndValueMessage) Reset()         { *m = KeyAndValueMessage{} }
func (m *KeyAndValueMessage) String() string { return proto.CompactTextString(m) }
func (*KeyAndValueMessage) ProtoMessage()    {}
func (*KeyAndValueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_statedb_2a3d28d9a5619618, []int{1}
}
func (m *KeyAndValueMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyAndValueMessage.Unmarshal(m, b)
}
func (m *KeyAndValueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyAndValueMessage.Marshal(b, m, deterministic)
}
func (dst *KeyAndValueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyAndValueMessage.Merge(dst, src)
}
func (m *KeyAndValueMessage) XXX_Size() int {
	return xxx_messageInfo_KeyAndValueMessage.Size(m)
}
func (m *KeyAndValueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyAndValueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KeyAndValueMessage proto.InternalMessageInfo

func (m *KeyAndValueMessage) GetKey() *KeyMessage {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyAndValueMessage) GetValue() *BytesMessage {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyMessage)(nil), "taraxa.vm.statedb.KeyMessage")
	proto.RegisterType((*KeyAndValueMessage)(nil), "taraxa.vm.statedb.KeyAndValueMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StateDBClient is the client API for StateDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateDBClient interface {
	Put(ctx context.Context, in *KeyAndValueMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*BytesMessage, error)
	Has(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*BoolMessage, error)
	Close(ctx context.Context, in *VmId, opts ...grpc.CallOption) (*empty.Empty, error)
}

type stateDBClient struct {
	cc *grpc.ClientConn
}

func NewStateDBClient(cc *grpc.ClientConn) StateDBClient {
	return &stateDBClient{cc}
}

func (c *stateDBClient) Put(ctx context.Context, in *KeyAndValueMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Delete(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Get(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*BytesMessage, error) {
	out := new(BytesMessage)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Has(ctx context.Context, in *KeyMessage, opts ...grpc.CallOption) (*BoolMessage, error) {
	out := new(BoolMessage)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Has", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateDBClient) Close(ctx context.Context, in *VmId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taraxa.vm.statedb.StateDB/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateDBServer is the server API for StateDB service.
type StateDBServer interface {
	Put(context.Context, *KeyAndValueMessage) (*empty.Empty, error)
	Delete(context.Context, *KeyMessage) (*empty.Empty, error)
	Get(context.Context, *KeyMessage) (*BytesMessage, error)
	Has(context.Context, *KeyMessage) (*BoolMessage, error)
	Close(context.Context, *VmId) (*empty.Empty, error)
}

func RegisterStateDBServer(s *grpc.Server, srv StateDBServer) {
	s.RegisterService(&_StateDB_serviceDesc, srv)
}

func _StateDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyAndValueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Put(ctx, req.(*KeyAndValueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Delete(ctx, req.(*KeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Get(ctx, req.(*KeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Has",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Has(ctx, req.(*KeyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateDB_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateDBServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taraxa.vm.statedb.StateDB/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateDBServer).Close(ctx, req.(*VmId))
	}
	return interceptor(ctx, in, info, handler)
}

var _StateDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taraxa.vm.statedb.StateDB",
	HandlerType: (*StateDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _StateDB_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StateDB_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StateDB_Get_Handler,
		},
		{
			MethodName: "Has",
			Handler:    _StateDB_Has_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StateDB_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statedb.proto",
}

func init() { proto.RegisterFile("statedb.proto", fileDescriptor_statedb_2a3d28d9a5619618) }

var fileDescriptor_statedb_2a3d28d9a5619618 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0x6b, 0x5b, 0x1c, 0xed, 0xc1, 0x3d, 0x68, 0xa9, 0xf8, 0x87, 0x82, 0x20, 0x08,
	0x5b, 0xa8, 0x08, 0xde, 0xa4, 0x31, 0x41, 0x4b, 0x11, 0x24, 0x42, 0x0f, 0x5e, 0x64, 0xd3, 0x1d,
	0x73, 0x30, 0xdb, 0x0d, 0xd9, 0x4d, 0x70, 0xc1, 0x83, 0xdf, 0xd2, 0xaf, 0x23, 0xf9, 0x87, 0xa8,
	0x89, 0xf1, 0xb8, 0xcc, 0x7b, 0xbf, 0x79, 0xf3, 0x58, 0x18, 0x28, 0xcd, 0x34, 0x72, 0x8f, 0x86,
	0x91, 0xd4, 0x92, 0xec, 0x68, 0x16, 0xb1, 0x57, 0x46, 0x13, 0x41, 0x8b, 0xc1, 0x68, 0xdf, 0x97,
	0xd2, 0x0f, 0x70, 0x92, 0x09, 0xbc, 0xf8, 0x79, 0x82, 0x22, 0xd4, 0x26, 0xd7, 0x8f, 0xb6, 0x57,
	0x52, 0x08, 0xb9, 0xce, 0x5f, 0xe3, 0xf7, 0x16, 0xc0, 0x02, 0xcd, 0x1d, 0x2a, 0xc5, 0x7c, 0x24,
	0x67, 0xb0, 0x91, 0x88, 0x39, 0x1f, 0xb6, 0x8e, 0x5b, 0xa7, 0x5b, 0xd3, 0x3d, 0xfa, 0x8b, 0x4d,
	0x97, 0x62, 0xce, 0xdd, 0x4c, 0x44, 0x1c, 0x18, 0x08, 0x14, 0x32, 0x32, 0x33, 0xce, 0x23, 0x54,
	0x6a, 0xd8, 0xce, 0x5c, 0x47, 0x15, 0x2e, 0xcb, 0x68, 0x54, 0xc5, 0x12, 0xf7, 0xbb, 0x6b, 0xfc,
	0x06, 0x64, 0x81, 0x66, 0xb6, 0xe6, 0x4b, 0x16, 0xc4, 0x58, 0x26, 0x99, 0x40, 0xe7, 0x05, 0x4d,
	0x11, 0xe4, 0xa0, 0x02, 0xf9, 0x95, 0xda, 0x4d, 0x95, 0xe4, 0x02, 0xba, 0x49, 0x0a, 0xf8, 0x6f,
	0x8a, 0x5c, 0x3d, 0xfd, 0x68, 0x43, 0xff, 0x21, 0x9d, 0xdb, 0x16, 0xb1, 0xa1, 0x73, 0x1f, 0x6b,
	0x72, 0x52, 0xbd, 0xed, 0x47, 0xc2, 0xd1, 0x2e, 0xcd, 0x6b, 0xa6, 0x65, 0xcd, 0xd4, 0x49, 0x6b,
	0x26, 0x57, 0xd0, 0xb3, 0x31, 0x40, 0x8d, 0xe4, 0xef, 0xd8, 0xb5, 0x00, 0x07, 0x3a, 0x37, 0xa8,
	0x9b, 0xdc, 0x4d, 0x07, 0xa6, 0xd7, 0xdc, 0x32, 0xd5, 0x84, 0x39, 0xac, 0xc2, 0x48, 0x19, 0x94,
	0x94, 0x4b, 0xe8, 0x5e, 0x07, 0x52, 0x21, 0xa9, 0xfb, 0x0c, 0x75, 0x67, 0x58, 0x9b, 0x8f, 0x7d,
	0x3f, 0x0a, 0x57, 0x4f, 0xbe, 0xf4, 0x7a, 0xd9, 0xe8, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0xf2, 0x68, 0x91, 0xbb, 0x02, 0x00, 0x00,
}
